[package]
edition = "2018"
name = "electron-sys"
version = "0.2.0"
authors = ["Darin Morrison <freebroccolo@users.noreply.github.com>"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/freebroccolo/electron-sys"
description = """
Raw bindings to the Electron API for projects using wasm-bindgen.
"""

[badges]
maintenance = { status = "experimental" }

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false
test = false

[dependencies.js-sys]
version = "^0.3.32"
features = []

[dependencies.wasm-bindgen]
version = "^0.2.55"
features = ["strict-macro"]

[dev-dependencies]
wasm-bindgen-test = { version = "=0.3.5" }

[workspace]
members = [
  "examples/quick-start/crates/app-main",
  "examples/quick-start/crates/app-renderer",
  "examples/quick-start-dodrio/crates/app-main",
  "examples/quick-start-dodrio/crates/app-renderer",
]
