[package]
name = "electron-sys"
version = "0.1.0"
authors = ["Darin Morrison <freebroccolo@users.noreply.github.com>"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/freebroccolo/electron-sys"
description = """
Raw bindings to the Electron API for projects using wasm-bindgen.
"""
edition = "2018"

[lib]

[dependencies]
serde = "^1.0.102"
serde_derive = "^1.0.102"

[dependencies.js-sys]
version = "^0.3.31"
features = []

[dependencies.web-sys]
version = "^0.3.31"
features = []

[dependencies.wasm-bindgen]
version = "^0.2.54"

[workspace]
members = [
  "examples/quick-start/crates/app-main",
  "examples/quick-start/crates/app-renderer",
  "examples/quick-start-dodrio/crates/app-main",
  "examples/quick-start-dodrio/crates/app-renderer",
]
