name: ci
on: [push, pull_request]
jobs:
  # skip ci if the last commit contains the appropriate tag
  skip-commit:
    name: Conditionally skip ci
    runs-on: ubuntu-latest
    steps:
      - if: "contains(github.event.head_commit.message, '[skip-ci]')
          || contains(github.event.head_commit.message, '[skip ci]')
          || contains(github.event.head_commit.message, '[ci-skip]')
          || contains(github.event.head_commit.message, '[ci skip]')"
        run: exit 78

  linux-cache-tools:
    name: Cache tools
    needs: [skip-commit]
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: 1.39.0
      RUSTC_WRAPPER: sccache
    steps:
      - uses: actions/checkout@v1
      - name: Prepare for restoring caches
        run: |
          rm -rf ~/.rustup
          rm -rf ~/.cargo/git
          rm -rf ~/.cargo/registry
      - name: Restore ~/.cargo/bin
        id: cache-cargo-bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('**/Cargo.lock') }}
      - name: Install sccache and wasm-pack
        if: steps.cache-cargo-bin.outputs.cache-hit != 'true'
        run: |
          curl -L      https://github.com/mozilla/sccache/releases/download/0.2.12/sccache-0.2.12-x86_64-unknown-linux-musl.tar.gz | tar zxf - --overwrite --strip-components=1 -C ~/.cargo/bin
          curl -L https://github.com/rustwasm/wasm-pack/releases/download/v0.8.1/wasm-pack-v0.8.1-x86_64-unknown-linux-musl.tar.gz | tar zxf - --overwrite --strip-components=1 -C ~/.cargo/bin
      - name: Restore ~/.rustup
        id: cache-rustup
        if: "steps.cache-cargo-bin-cargo-audit.outputs.cache-hit != 'true'"
        uses: actions/cache@v1
        with:
          path: ~/.rustup
          key: rustup-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('rust-toolchain') }}
      - name: Install rust toolchain
        if: "steps.cache-cargo-bin-cargo-audit.outputs.cache-hit != 'true'
          && steps.cache-rustup               .outputs.cache-hit != 'true'"
        run: |
          rustup set profile minimal
          rustup toolchain install $RUST_TOOLCHAIN --component clippy rustfmt
      - name: Restore ~/.cache/sccache
        id: cache-sccache
        if: "steps.cache-cargo-bin-cargo-audit.outputs.cache-hit != 'true'"
        uses: actions/cache@v1
        with:
          path: ~/.cache/sccache
          key: ccache-${{ runner.OS }}-s${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/git
        id: cache-cargo-git
        if: "steps.cache-cargo-bin-cargo-audit.outputs.cache-hit != 'true'"
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: cargo-git-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/registry
        id: cache-cargo-registry
        if: "steps.cache-cargo-bin-cargo-audit.outputs.cache-hit != 'true'"
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo fetch
        if: " steps.cache-cargo-bin-cargo-audit.outputs.cache-hit != 'true'
          && (steps.cache-cargo-git            .outputs.cache-hit != 'true'
          ||  steps.cache-cargo-registry       .outputs.cache-hit != 'true'
          ||  steps.cache-target               .outputs.cache-hit != 'true')"
        run: cargo fetch
      - name: Install cargo-audit
        if: "steps.cache-cargo-bin-cargo-audit.outputs.cache-hit != 'true'"
        run: cargo install cargo-audit

  # verify that Cargo.lock passes audit
  linux-cargo-audit:
    name: Run cargo audit
    needs: [skip-commit, linux-cache-tools]
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: 1.39.0
      RUSTC_WRAPPER: sccache
    steps:
      - uses: actions/checkout@v1
      - name: Prepare for restoring caches
        run: |
          rm -rf ~/.rustup
          rm -rf ~/.cargo/git
          rm -rf ~/.cargo/registry
      - name: Restore ~/.rustup
        id: cache-rustup
        uses: actions/cache@v1
        with:
          path: ~/.rustup
          key: rustup-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('rust-toolchain') }}
      - name: Restore ~/.cache/sccache
        id: cache-sccache
        uses: actions/cache@v1
        with:
          path: ~/.cache/sccache
          key: sccache-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/bin
        id: cache-cargo-bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/bin/cargo-audit
        id: cache-cargo-bin-cargo-audit
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin/cargo-audit
          key: cargo-bin-cargo-audit-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/git
        id: cache-cargo-git
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: cargo-git-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/registry
        id: cache-cargo-registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ./target
        id: cache-target
        uses: actions/cache@v1
        with:
          path: target
          key: cargo-build-target-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo audit
        uses: actions-rs/cargo@v1
        with:
          command: audit

  # verify that project builds (via "check" via "clippy") on linux
  linux-cargo-clippy:
    name: Run cargo clippy
    needs: [skip-commit, linux-cache-tools]
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: 1.39.0
      RUSTC_WRAPPER: sccache
    steps:
      - uses: actions/checkout@v1
      - name: Prepare for restoring caches
        run: |
          rm -rf ~/.rustup
          rm -rf ~/.cargo/git
          rm -rf ~/.cargo/registry
      - name: Restore ~/.rustup
        id: cache-rustup
        uses: actions/cache@v1
        with:
          path: ~/.rustup
          key: rustup-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('rust-toolchain') }}
      - name: Restore ~/.cache/sccache
        id: cache-sccache
        uses: actions/cache@v1
        with:
          path: ~/.cache/sccache
          key: sccache-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/bin
        id: cache-cargo-bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/git
        id: cache-cargo-git
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: cargo-git-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/registry
        id: cache-cargo-registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ./target
        id: cache-target
        uses: actions/cache@v1
        with:
          path: target
          key: cargo-build-target-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --frozen --all-features --all-targets -- -D warnings

  # build the documentation
  linux-cargo-docs:
    name: Run cargo docs
    needs: [skip-commit, linux-cache-tools]
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: 1.39.0
    steps:
      - uses: actions/checkout@v1
      - name: Prepare for restoring caches
        run: |
          rm -rf ~/.rustup
          rm -rf ~/.cargo/git
          rm -rf ~/.cargo/registry
      - name: Restore ~/.rustup
        id: cache-rustup
        uses: actions/cache@v1
        with:
          path: ~/.rustup
          key: rustup-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('rust-toolchain') }}
      - name: Restore ~/.cache/sccache
        id: cache-sccache
        uses: actions/cache@v1
        with:
          path: ~/.cache/sccache
          key: sccache-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/git
        id: cache-cargo-git
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: cargo-git-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/registry
        id: cache-cargo-registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ./target
        id: cache-target
        uses: actions/cache@v1
        with:
          path: target
          key: cargo-build-target-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --frozen --all-features --no-deps --package electron-sys
      - env:
          PERSONAL_TOKEN: ${{ secrets.ACTIONS_GH_PAGES_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/doc
          SCRIPT_MODE: true
        run: wget -qO - https://raw.githubusercontent.com/interfaces-rs/actions-gh-pages/v2.5.1/entrypoint.sh | bash -

  # verify that code is formatted
  linux-cargo-fmt:
    name: Run cargo fmt
    needs: [skip-commit, linux-cache-tools]
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: nightly
    steps:
      - uses: actions/checkout@v1
      - name: Prepare for restoring caches
        run: |
          rm -rf ~/.rustup
      - name: Restore ~/.rustup
        id: cache-rustup
        uses: actions/cache@v1
        with:
          path: ~/.rustup
          key: rustup-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('rust-toolchain') }}
      - name: Install rust toolchain
        if: steps.cache-rustup.outputs.cache-hit != 'true'
        run: |
          rustup set profile minimal
          rustup toolchain install $RUST_TOOLCHAIN --component clippy rustfmt
      - if: "steps.cache-cargo-git     .outputs.cache-hit != 'true'
          || steps.cache-cargo-registry.outputs.cache-hit != 'true'
          || steps.cache-target        .outputs.cache-hit != 'true'"
        run: cargo "+$RUST_TOOLCHAIN" fetch
      - name: Run cargo fmt
        run: cargo "+$RUST_TOOLCHAIN" fmt --all -- --check

  # verify that tests pass on linux
  linux-cargo-test:
    name: Run cargo test
    needs: [skip-commit, linux-cache-tools]
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: 1.39.0
      RUSTC_WRAPPER: sccache
    steps:
      - uses: actions/checkout@v1
      - name: Prepare for restoring caches
        run: |
          rm -rf ~/.rustup
          rm -rf ~/.cargo/git
          rm -rf ~/.cargo/registry
      - name: Restore ~/.rustup
        id: cache-rustup
        uses: actions/cache@v1
        with:
          path: ~/.rustup
          key: rustup-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('rust-toolchain') }}
      - name: Restore ~/.cache/sccache
        id: cache-sccache
        uses: actions/cache@v1
        with:
          path: ~/.cache/sccache
          key: sccache-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/bin
        id: cache-cargo-bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.OS }}-[${{ env.RUST_TOOLCHAIN }}]-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/git
        id: cache-cargo-git
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: cargo-git-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ~/.cargo/registry
        id: cache-cargo-registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Restore ./target
        id: cache-target
        uses: actions/cache@v1
        with:
          path: target
          key: cargo-build-target-${{ runner.OS }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Configure node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm ci
      - run: wasm-pack test --node -- --frozen --all-features --all-targets
